### ISSUE TITLE
Console crashed.

### ISSUE THREAD

**Issue by dethompson1958** [peted-davis/WeatherFlow_PiConsole#69] opened 2022-12-03 06:16 UTC
**Describe the bug**
Console had crashed.  Tried to restart using "wfpiconsole start" and the UI flashed and nothing happened.  Tried rebooting the PI and trying again to start console and nothing happens.  Tried to attach screen shot of attempting to start from the terminal.
**To Reproduce**

**Screenshots**
![16700477822618040205065278548441](https://user-images.githubusercontent.com/66026152/205427355-c51ebd4c-3066-4e65-afda-403591e18f1f.jpg)

**Hardware/OS/Version (please complete the following information):**
 - OS: [e.g. Raspberry Pi OS Bullseye]
 - Hardware: [e.g. Pi3]
 - Console Version: [e.g. 22.3.1]

**Additional context**

**Comment by Grandmasg** [comment] 2022-12-03 06:23
Same issue --> https://github.com/peted-davis/WeatherFlow_PiConsole/issues/68

**Comment by philbert2k** [comment] 2022-12-03 06:24
Here as well. Not sure if this could be related to server maintenance somewhere (based on the error) but will keep checking and watching here.

**Comment by Kuuke** [comment] 2022-12-03 06:32
Glad I'm not the only one ;)

OS: Raspberry Pi Bullseye
Hardware: RPI4
Python: 3.9
WFPI Console version: 22.5.1

**Comment by Grandmasg** [comment] 2022-12-03 06:48
Temp fix --> https://github.com/peted-davis/WeatherFlow_PiConsole/issues/68#issuecomment-1336097746

**Comment by peted-davis** [comment] 2022-12-03 07:28
Thanks for the report, I will look into this ASAP (probably Monday at the latest)

**Comment by lorick57** [comment] 2022-12-03 12:36
Same here

**Comment by peted-davis** [comment] 2022-12-03 14:49
Duplicate of #68

**Closed by peted-davis** 2022-12-03 14:49 UTC

**Comment by dethompson1958** [comment] 2022-12-03 17:15
Thanks for the quick fix.  All is working great after update.  Thanks again.
